service: s3-sls-crud

frameworkVersion: '3.38.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  environment:
    NODE_ENV: dev

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get